#https://github.com/revolunet/create-react-app-circleci/blob/master/.circleci/config.yml
# 给当前node_modules 一个快照，如果 package.json 没变，node_modules 就不用重新下载
defaults: &defaults
  docker:
    - image: circleci/node:12.18.2

version: 2
jobs:
  publish:
    <<: *defaults
    steps:
      - checkout
      - run: git pull
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: npm install -D @cloudflare/wrangler --registry.npmjs.org
      # ksgcLbaW4SVNXtGtudlBOZ2EfMJz80TMlqpNi934
      - run: echo ksgcLbaW4SVNXtGtudlBOZ2EfMJz80TMlqpNi934 | npx wrangler config 
      - run: npx wrangler publish
      # - run: CF_EMAIL=$CF_EMAIL CF_API_KEY=$CF_API_KEY wrangler publish
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - node_modules


workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - publish
      # - prepare
      # - publish:
      #     requires:
      #       - prepare
#      - prepare
#      - build:
#          requires:
#            - test
#      - test:
#          requires:
#            - prepare
#          requires:
#            - build
#          filters:
#            # 所有 branches 都忽略，只部署 vx.x.x 的 tags
##            tags:
##              only: /^v[0-9]+(\.[0-9]+)*/
#            branches:
#              all
#              ignore: /.*/